version: 0.0.{build}

init:
- git config --global core.autocrlf true

branches:
  only:
  - master

image: Visual Studio 2019

configuration:
- Debug
- Develop
- Release

platform:
- x64

build_script:
- cmake -S"." -b".\build" -G"Visual Studio 16 2019"
- cmake --build build

build:
  verbosity: normal