version: 0.0.{build}

init:
- git config --global core.autocrlf true

branches:
  only:
  - master

image:
- Visual Studio 2019

configuration:
- Debug
- Develop
- Release

platform:
- x64

before_build:
- cmd: cmake -S. -B./build -G"Visual Studio 16 2019"

build:
  project: build/rtek.sln
  verbosity: normal